spring:
  application:
  name: activityservices
  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness
      database: aiactivityfitness


eureka:
  client:
    defaultZone: http://localhost:8761/eureka/



server:
  port: 8082
